### ISSUE TITLE
Factorial of 0?

### ISSUE THREAD

**Issue by 1bit23** [vtcbca/23bit-basic-programming-Python-Programming-GU#1]
factorial of 0 is 1 but my program is giving 0 in output.

**Comment by 80bit23** [comment]
nothing wrong with your program, its just 0 is a spacial case.

**Comment by 1bit23** [comment]
what special case???

**Comment by 80bit23** [comment]
0!=1 & 1!=1

**Comment by 1bit23** [comment]
what is this exclamation mark?

**Comment by 7bit23** [comment]
it is sign of factorial. just add a condition for zero and complete it.

**Comment by 1bit23** [comment]
ok i added it thank both of you for your support.
