### ISSUE TITLE
Every Number is as Prime

### ISSUE THREAD

**Issue by 7bit23** [vtcbca/23bit-basic-programming-Python-Programming-GU#2]
My prime program outputs every number as prime. I think I missed something in maths

**Comment by 80bit23** [comment]
i think you just ckecked that it is devided by 1 and not any other number

**Comment by 7bit23** [comment]
can you explain like  i am 5 year old??

**Comment by 80bit23** [comment]
prime number jo he na, vo bas do number se divisible he. 
1 & vo kud bas
samaj me aya?

**Comment by 7bit23** [comment]
ha thoda thoda

**Comment by 80bit23** [comment]
dekh 2 bas do number se divide hota he 1 and 2 to vo prime number he.
3 bhi bas 1 and 3 se divide hota he to vo bhi prime number he.
par 4 nahi he kyu ki vo 1 ,2 and 4 se divide hota he.
ab samaja?

**Comment by 7bit23** [comment]
maltab jo number sirf do numbero se divisible he vo prime number he right?

**Comment by 80bit23** [comment]
absolutely right

**Comment by 7bit23** [comment]
thanks, magar ye prime number ka me kya karu ?

**Comment by 80bit23** [comment]
koi programm me use hota hogaa, dekhenge.

**Comment by 7bit23** [comment]
thank ab correct result aa raha he
