### ISSUE TITLE
increase and decrease alfabet in assignment 8

### ISSUE THREAD

**Issue by 80bit23** [vtcbca/23bit-basic-programming-Python-Programming-GU#3]
how do i change A to B

**Comment by 7bit23** [comment]
you need to us ASCII values

**Comment by 80bit23** [comment]
what it that?

**Comment by 7bit23** [comment]
all the alfabet have int values you change in it and alfabet will also change.

**Comment by 80bit23** [comment]
i am still confused

**Comment by 7bit23** [comment]
A has ascii value of integer 65, if you change that number to 66 and print in character format it will display as B

**Comment by 80bit23** [comment]
ok so just like number pattern but just need to use character data type is that what you are saying??

**Comment by 80bit23** [comment]
yes

**Comment by 1bit23** [comment]
yes

**Comment by 80bit23** [comment]
thanks you.
