### ISSUE TITLE
my pattern is in line.

### ISSUE THREAD

**Issue by 7bit23** [vtcbca/23bit-basic-programming-Python-Programming-GU#5]
![line patten](https://github.com/user-attachments/assets/8314590b-bcae-4363-bb8e-99b9c70f5041)

**Comment by 80bit23** [comment]
i think you forgot a to put \n in loop

**Comment by 7bit23** [comment]
i have put it and but now its a vertical line

**Comment by 7bit23** [comment]
![vertical l](https://github.com/user-attachments/assets/491ae7d2-6725-4d70-a9a5-c47f39cbc1ce)

**Comment by 80bit23** [comment]
did you add two?

**Comment by 7bit23** [comment]
yes because you said add it in loop

**Comment by 80bit23** [comment]
not in all, just when you change lines.

**Comment by 7bit23** [comment]
i dont understand.

**Comment by 80bit23** [comment]
you dont need new line in second loop because you want to print in line , but you need new line in first loop because we are changing the line.

**Comment by 7bit23** [comment]
oh now i understand.

**Comment by 7bit23** [comment]
![vertical l](https://github.com/user-attachments/assets/82ae2204-2a59-4d4a-8a0b-46d495deaa7c)

**Comment by 80bit23** [comment]
congratulation 👍

**Comment by 7bit23** [comment]
you are the expert in pattern

**Comment by 80bit23** [comment]
its just practice.

**Comment by 7bit23** [comment]
god gave you good brain

**Comment by 80bit23** [comment]
lol

**Comment by 7bit23** [comment]
please help me again in future
